# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatosPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('capacitacion', models.BooleanField(verbose_name='desea usted una capacitacion laboral?')),
                ('tema', models.TextField(blank=True, null=True, verbose_name='que otro tema usted considera como importante para ser incluidodentro de una capacitacion?')),
                ('motivado', models.BooleanField(verbose_name='se encuentra motivado para seguir realizando otros estudios?')),
                ('motivacion', models.TextField(blank=True, null=True, verbose_name='que lo motiva a usted a prepararse mas academicamente?')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Labores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NivelDeEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datospersonas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Labores', verbose_name='Selecione en que area necesita usted capacitarse para desarrollar sus labores diarias'),
        ),
        migrations.AddField(
            model_name='datospersonas',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Cargo'),
        ),
        migrations.AddField(
            model_name='datospersonas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso', verbose_name='De acuerdo a la respuesta, en cual de las siguientes areas desea capacitarse'),
        ),
        migrations.AddField(
            model_name='datospersonas',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Departamento'),
        ),
        migrations.AddField(
            model_name='datospersonas',
            name='nivel_cademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.NivelDeEstudio'),
        ),
    ]
