# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonas',
            name='motivado',
            field=models.BooleanField(),
        ),
    ]
